# API_INFO
DROP TABLE IF EXISTS `API_INFO`;
CREATE TABLE `API_INFO` (
  API_INFO_KEY VARCHAR(50),
  TARGET_API VARCHAR(50),
  CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (API_INFO_KEY)
);

# KEY_INFO
DROP TABLE IF EXISTS `KEY_INFO`;
CREATE TABLE `KEY_INFO` (
  KEY_INFO_KEY VARCHAR(50),
  API_INFO_KEY VARCHAR(50),
  KEY_ITEM VARCHAR(50),
  ITEM_SECTION VARCHAR(50),
  CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (KEY_INFO_KEY)
);

# RESPONSE
DROP TABLE IF EXISTS `RESPONSE`;
CREATE TABLE `RESPONSE` (
  RESPONSE_KEY VARCHAR(50),
  KEY_INFO_KEY VARCHAR(50),
  KEY_VALUE VARCHAR(100),
  HTTPSTATUS INT,
  RE_TELEGRAM VARCHAR(2000),
  SLEEP_TIME INT,
  CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (RESPONSE_KEY, KEY_INFO_KEY)
);
